name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Restore tools
      run: dotnet tool restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Restore demo tools
      run: dotnet tool restore
      working-directory: ./demo

    - name: Build Demo
      run: npm run build
      working-directory: ./demo